openapi: 3.1.0
info:
  title: E-Commerce API
  version: 1.0.0
servers:
  - url: http://localhost:3000/api
tags:
  - name: Products
    description: Product-related endpoints
  - name: Orders
    description: Order-related endpoints

paths:
  /products:
    $ref: './paths/products.yaml'
  /products/{id}:
    $ref: './paths/products{id}.yaml'
  /orders:
    $ref: './paths/orders.yaml'
  /orders/{id}:
    $ref: './paths/orders{id}.yaml'
